#!/usr/bin/env python3
"""
Script to translate Russian text in markdown files to English.
Replaces common Russian phrases with English equivalents.
"""

import os
import re

# Mapping of Russian phrases to English
REPLACEMENTS = {
    # Real Cyoda section
    "✅ Реальные Cyoda Credentials добавлены": "✅ Real Cyoda Credentials Added",
    "Приложение теперь настроено на подключение к реальному Cyoda EU instance": "Application is now configured to connect to a real Cyoda EU instance",
    "Запуск с реальной Cyoda": "Running with Real Cyoda",
    "Использовать скрипт (RECOMMENDED)": "Use Script (RECOMMENDED)",
    "Скрипт автоматически": "Script automatically",
    "Устанавливает Java path": "Sets Java path",
    "Собирает проект": "Builds project",
    "Запускает приложение с реальными credentials": "Runs application with real credentials",
    "Ручной запуск": "Manual Run",
    "Через environment variables": "Via Environment Variables",
    "Verification подключения": "Connection Verification",
    "Запустить приложение": "Start Application",
    "Check статус gRPC": "Check gRPC Status",
    "Получить токен": "Get Token",
    "Check gRPC статус": "Check gRPC Status",
    "Ожидаемый результат": "Expected Result",
    "Check логи": "Check Logs",
    "Ищите в логах": "Look for in logs",
    "Безопасность": "Security",
    "IMPORTANT: Не коммитить credentials в git!": "IMPORTANT: Do not commit credentials to git!",
    "Не коммитить credentials в git": "Do not commit credentials to git",
    "Credentials уже добавлены в": "Credentials are already added to",
    "Для production": "For production",
    "Удалить credentials из": "Remove credentials from",
    "Использовать environment variables": "Use environment variables",
    "Использовать secrets management": "Use secrets management",
    "Очистить": "Clean",
    "Установить переменные окружения": "Set environment variables",
    "Запустить": "Run",
    "Файлы конфигурации": "Configuration Files",
    "Пример файла с переменными окружения": "Example file with environment variables",
    "Скопируйте в .env и обновите значения": "Copy to .env and update values",
    "Скрипт для запуска с реальными credentials": "Script for running with real credentials",
    "Основной конфиг приложения": "Main application config",
    "Содержит credentials для разработки": "Contains credentials for development",
    "Тестирование с реальной Cyoda": "Testing with Real Cyoda",
    "Запустить все тесты": "Run all tests",
    "Check gRPC соединение": "Check gRPC Connection",
    "Переподключиться к Cyoda": "Reconnect to Cyoda",
    "Решение проблем": "Troubleshooting",
    "Проблема: \"Unable to resolve host\"": "Problem: \"Unable to resolve host\"",
    "Решение": "Solution",
    "Проверить интернет соединение": "Check internet connection",
    "Проверить что Cyoda сервер доступен": "Check that Cyoda server is available",
    "Проверить DNS резолюцию": "Check DNS resolution",
    "Проблема: \"Failed to get access token\"": "Problem: \"Failed to get access token\"",
    "Проверить что credentials правильные": "Check that credentials are correct",
    "Проверить логи для деталей ошибки": "Check logs for error details",
    "Проблема: \"TRANSIENT_FAILURE\"": "Problem: \"TRANSIENT_FAILURE\"",
    "Это нормально при первом подключении": "This is normal on first connection",
    "Приложение автоматически переподключится": "Application will automatically reconnect",
    "Статус подключения": "Connection Status",
    "Возможные состояния": "Possible States",
    "Состояние": "Status",
    "Описание": "Description",
    "Неактивно": "Idle",
    "Подключается": "Connecting",
    "Готово": "Ready",
    "Временная ошибка": "Temporary error",
    "Переподключается": "Reconnecting",
    "Отключено": "Shutdown",
    "Итог": "Summary",
    "Приложение теперь полностью интегрировано с реальной Cyoda EU instance": "Application is now fully integrated with real Cyoda EU instance",
    "Запустить": "Run",
    "Тестировать": "Test",
    # Common phrases
    "Что было сделано": "What was done",
    "Что происходит": "What happens",
    "Что изменилось": "What changed",
    "Что проверяется": "What is checked",
    "Главные улучшения": "Main improvements",
    "Главные особенности": "Key features",
    "Ключевые улучшения": "Key improvements",
    "Ключевые особенности": "Key features",
    "Быстрый старт": "Quick start",
    "Быстрый справочник": "Quick reference",
    "Быстро тестировать": "Quick testing",
    "Подготовка": "Preparation",
    "Шаг": "Step",
    "Этап": "Phase",
    "Фаза": "Phase",
    "Результат": "Result",
    "Результаты": "Results",
    "Проверить": "Check",
    "Проверка": "Verification",
    "Тестирование": "Testing",
    "Успешное завершение": "Successful completion",
    "Завершено": "Complete",
    "ПОЛНАЯ ИНСТРУКЦИЯ": "FULL INSTRUCTIONS",
    "ПОЛНЫЙ ПОРЯДОК ТЕСТИРОВАНИЯ": "FULL TEST ORDER",
    "ПО ТРЕБОВАНИЯМ": "BY REQUIREMENTS",
    "РЕКОМЕНДУЕТСЯ": "RECOMMENDED",
    "ОБЯЗАТЕЛЬНО": "MANDATORY",
    "ВАЖНО": "IMPORTANT",
    "ВНИМАНИЕ": "ATTENTION",
    "ОШИБКА": "ERROR",
    "РЕШЕНИЕ": "SOLUTION",
    "Решение проблем": "Troubleshooting",
    "Решение": "Solution",
    "Проблема": "Problem",
    "Проблемы": "Problems",
    "Проблема не работает": "Doesn't work",
    "Стиль загрузки файлов": "File upload style",
    "Загрузка файлов": "File upload",
    "Загрузить файл": "Upload file",
    "Загружает": "Loads",
    "Загружаются": "Are loaded",
    "Загруженных": "Uploaded",
    "Загруженные": "Uploaded",
    "Удаление": "Deletion",
    "Удалены": "Deleted",
    "Удаляет": "Deletes",
    "Удаления": "Deletion",
    "Документация": "Documentation",
    "Документ": "Document",
    "Файловая структура": "File structure",
    "Структура файлов": "File structure",
    "Интеграция": "Integration",
    "Интегрируйте": "Integrate",
    "Интегрировано": "Integrated",
    "Подключение": "Connection",
    "Подключить": "Connect",
    "Подключение к": "Connecting to",
    "Подключены": "Connected",
    "Статус подключения": "Connection status",
    "Возможные состояния": "Possible states",
    "Состояние": "Status",
    "Состояния": "States",
    "Конфигурация": "Configuration",
    "Переименовать": "Rename",
    "Удалить": "Delete",
    "Обновить": "Update",
    "Обновлены": "Updated",
    "Обновления": "Updates",
    "Создать": "Create",
    "Созданные": "Created",
    "Созданы": "Created",
    "Созданный": "Created",
    "Сохранить": "Save",
    "Сохранены": "Saved",
    "Сохранения": "Saves",
    "Скопировать": "Copy",
    "Скопировать новые": "Copy new",
    "Файлы уже созданы": "Files already created",
    "Заменить": "Replace",
    "Замените": "Replace",
    "Заменены": "Replaced",
    "Замена": "Replacement",
    "Код дефектов": "Defects code",
    "Синхронизация": "Synchronization",
    "Синхронизировать": "Synchronize",
    "Валидация": "Validation",
    "Валидировать": "Validate",
    "Требования": "Requirements",
    "Требуемые": "Required",
    "Требуется": "Required",
    "Требует": "Requires",
    "Список": "List",
    "Список проектов": "Project list",
    "Список прогонов": "Run list",
    "Список эндпоинтов": "Endpoint list",
    "Список тестов": "Test list",
    "Надстройка": "Extension",
    "Надстройки": "Extensions",
    "Полезно": "Useful",
    "Использование": "Usage",
    "Используйте": "Use",
    "Используется": "Is used",
    "Примеры": "Examples",
    "Пример": "Example",
    "Пример использования": "Usage example",
    "Примеры в": "Examples in",
    "Примечание": "Note",
    "Примечания": "Notes",
    "Описание": "Description",
    "Описав": "Described",
    "Описанием": "Described",
    "Обозначения": "Designations",
    "Обозначается": "Is designated",
    "Обозначение": "Notation",
    "Добавлены": "Added",
    "Добавлено": "Added",
    "Добавить": "Add",
    "Добавляет": "Adds",
    "Добавляются": "Are added",
    "Добавления": "Addition",
    "Добавления новые": "Add new",
    # More complex phrases
    "ФАЗА": "PHASE",
    "эндпоинтов": "endpoints",
    "работают": "work",
    "тестирование": "testing",
    "Все": "All",
    "сохранено": "saved",
    "не": "not",
    "Поле": "Field",
    "эндпоинта": "endpoint",
    "токены": "tokens",
    "содержит": "contains",
    "приложение": "application",
    "поле": "field",
    "обновлён": "updated",
    "Вариант": "Option",
    "через": "via",
    "то": "that",
    "тестирования": "testing",
    "проект": "project",
    "ответа": "response",
    "из": "from",
    "все": "all",
    "Ручное": "Manual",
    "Оба": "Both",
    "Запустить": "Start",
    "Если": "If",
    "ПОЛНАЯ ИНСТРУКЦИЯ ПО РУЧНОМУ ТЕСТИРОВАНИЮ": "FULL MANUAL TESTING INSTRUCTIONS",
    "Полный порядок тестирования": "Full testing order",
    "Полное руководство по ручному тестированию": "Full manual testing guide",
    "AUTHENTICATION": "AUTHENTICATION",
    "PROJECTS": "PROJECTS",
    "SUITES": "SUITES",
    "TEST CASES": "TEST CASES",
    "TEST STEPS": "TEST STEPS",
    "TEST RUNS": "TEST RUNS",
    "ADMIN GRPC": "ADMIN GRPC",
    "Финальный чеклист": "Final Checklist",
    "финальный": "final",
    "Быстрый старт": "Quick Start",
    "быстрый": "quick",
    "Что происходит": "What happens",
    "что происходит": "what happens",
    "Что проверяется": "What is checked",
    "Полное руководство": "Full guide",
    "полное": "full",
    "порядок": "order",
    "Порядок": "Order",
    "Проверить": "Check",
    "проверить": "check",
    "Проверка": "Verification",
    "Окружение": "Environment",
    "окружение": "environment",
    "Статус": "Status",
    "статус": "status",
    "Завершить": "Complete",
    "завершить": "complete",
    "Разблокировать": "Unlock",
    "разблокировать": "unlock",
    "Заблокировать": "Lock",
    "заблокировать": "lock",
    "Удалить": "Delete",
    "удалить": "delete",
    "Обновить": "Update",
    "обновить": "update",
    "Создать": "Create",
    "создать": "create",
    "Сохранить": "Save",
    "сохранить": "save",
    "сохранён": "saved",
    "сохранены": "saved",
    "Заголовок": "Title",
    "заголовок": "title",
    "Описание": "Description",
    "описание": "description",
    "Приоритет": "Priority",
    "приоритет": "priority",
    "Высокий": "High",
    "высокий": "high",
    "Средний": "Medium",
    "средний": "medium",
    "Низкий": "Low",
    "низкий": "low",
    "Вполнении": "In Progress",
    "в процессе": "in progress",
    "завершено": "completed",
    "Завершено": "Completed",
    "успешно": "successfully",
    "ошибка": "error",
    "Ошибка": "Error",
    "Успешно": "Successfully",
    "Итого": "Total",
    "итого": "total",
    "Примеры": "Examples",
    "примеры": "examples",
    "Пример": "Example",
    "пример": "example",
    "смотреть": "view",
    "Смотреть": "View",
}

def translate_file(filepath):
    """Translate Russian text to English in a file."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original_content = content
    
    # Apply replacements
    for russian, english in REPLACEMENTS.items():
        # Case-sensitive replacement
        content = content.replace(russian, english)
    
    # Write back if changed
    if content != original_content:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False

# Files to process
files_to_translate = [
    "./apps/backend/API_TESTING_GUIDE.md",
    "./apps/backend/CYODA_INTEGRATION.md",
    "./apps/backend/MANUAL_TESTING_INSTRUCTIONS.md",
    "./apps/backend/README_TESTING.md",
    "./apps/backend/SCHEMA_AND_WORKFLOW_IMPORT.md",
    "./apps/backend/docs/UI_REQUIREMENTS.md",
    "./.claude/worktrees/stoic-cray/backend/API_TESTING_GUIDE.md",
    "./.claude/worktrees/stoic-cray/backend/CYODA_INTEGRATION.md",
    "./.claude/worktrees/stoic-cray/backend/MANUAL_TESTING_INSTRUCTIONS.md",
    "./.claude/worktrees/stoic-cray/backend/README_TESTING.md",
]

if __name__ == "__main__":
    for filepath in files_to_translate:
        if os.path.exists(filepath):
            if translate_file(filepath):
                print(f"✅ Translated: {filepath}")
            else:
                print(f"⊘ No changes: {filepath}")
        else:
            print(f"⚠️  File not found: {filepath}")
